### ISSUE TITLE
Error while inspecting an item

### ISSUE THREAD

**Issue by MrLarkyy** [Citrinate/CS2Interface#14]
![image](https://github.com/Citrinate/CS2Interface/assets/48769171/7dbe2159-205d-4733-bba1-d3b3345b0163)
Hey! Am getting this error when I try to inspect an item.

**Comment by Citrinate** [comment]
The latest build here should fix this: [CS2Interface V1.0.10.1](https://github.com/Citrinate/CS2Interface/actions/runs/8767945584/artifacts/1432402177)
