### ISSUE TITLE
Contract/Craft

### ISSUE THREAD

**Issue by OliverTrust** [Citrinate/CS2Interface#15]
Is it possible to add this feature to this plugin?

**Comment by Citrinate** [comment]
Yes it's possible.  I'll try to get this into the next release.

**Comment by Citrinate** [comment]
I've finally got around to adding this.  I have more features planned for V1.1 however, and so this still won't be released for a while.

If you care to test it, the latest V1.1 build is here: https://github.com/Citrinate/CS2Interface/actions/runs/12306204379/artifacts/2314633993 (future builds will show up here: https://github.com/Citrinate/CS2Interface/actions?query=branch%3A1.1)

V1.1 README is here: https://github.com/Citrinate/CS2Interface/tree/1.1
