### ISSUE TITLE
inode bug

### ISSUE THREAD

**Issue by feeops** [Citrinate/CS2Interface#16]
I use asf and cs2interface for 3 accounts.
I add item to storage and remove item from storage every hours.

When I run asf for some days or a week.

There is a error.

DebugNetworkListener threw an exception: System.IO.IOException: No space left on device

But my linux server has a lot space on device.

I find linux inode is full.I must delete the asf folder and rebuild it.

**Comment by feeops** [comment]
I change the asf debug from true to false.It will reduce the log

**Comment by Citrinate** [comment]
ASF's debug mode creates a file for every message it sends or receives from Steam.  Debug mode is not meant to be used unless there's a reason for it, and you would have ran out of inodes even if you weren't using this plugin.  If there's no reason why you should feel the need to use debug mode with this plugin then this really isn't a plugin issue.
