### ISSUE TITLE
GC limitation

### ISSUE THREAD

**Issue by OliverTrust** [Citrinate/CS2Interface#22]
I can't start CS2 Interface with more than three bots at same time.
Is any way to avoid this limitation?

**Comment by Citrinate** [comment]
What version of ASF are you using?  Is the issue only with starting the interface with more than 3 bots at the same time (as in you can have more, but only if you delay in starting them)?  Also what errors are you getting?

**Comment by OliverTrust** [comment]
Wow, these were problems with free accounts (and without cs prime). Tried on 50 with paid (5$) and primes and everything works!
