### ISSUE TITLE
Can you develop a software of CS2Interface without ArchiSteamFarm?

### ISSUE THREAD

**Issue by feeops** [Citrinate/CS2Interface#7]
ArchiSteamFarm is base on [SteamKit2](https://github.com/SteamRE/SteamKit)

Can you  develop CS2Interface base on SteamKit2?

**Comment by Citrinate** [comment]
Sure, it can be done.  Although software that connects to CS2 must first connect to Steam, and that's what ASF handles very well.  If someone wanted to design a project like this not using ASF, they'd first need to re-implement many of the features that ASF already has.  Obviously, this being an ASF plugin, nothing like that is going to be happening here.
