### ISSUE TITLE
What is the use case?

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/CS2Interface#9]
I have never tried this plugin and always wondered what it was used for. Would you mind clarifying the use case is for this plugin?

**Comment by Citrinate** [comment]
It's only use is in the development of other projects.  I use it as part of a private project for managing crate contents.  It can be thought of as an alternative to something like [node-globaloffensive](https://github.com/DoctorMcKay/node-globaloffensive) or [csfloat/inspect](https://github.com/csfloat/inspect).  Currently though, the plugin only has the bare minimum of features needed for my own use case.

It would be possible to add commands for various CS2 actions that make the plugin more generally useful, but that's not a part of my plans for this plugin.

**Comment by woctezuma** [comment]
Thank you!

**Comment by MrLarkyy** [comment]
Sorry for re-opening, but can the actual inspect method create a screenshot of the inspected gun? As Swap.gg does? Am trying to find a way of how to do that thing

**Comment by Citrinate** [comment]
> Sorry for re-opening, but can the actual inspect method create a screenshot of the inspected gun? As Swap.gg does? Am trying to find a way of how to do that thing

This isn't something the plugin currently does and I'm not planning on implementing something like this.  The plugin will sometimes return an image of an item when inspecting, but this is just a generic image used for all copies of a skin.

Example: https://media.steampowered.com/apps/730/icons/econ/default_generated/weapon_awp_cu_awp_wildfire_light_large.61e36b12eb45a39836cdb5badb5a536737684861.png
